### ISSUE TITLE
Individual Tests for  test developers

### ISSUE THREAD

**Issue by mydatascience** [lf-edge/eden#107]
Layer 2- for developers that wanna develop tests. 
Test for them is a folder where they define: 

1) eden-config.tmpl - which has the local config for the test including patterns. 

2) <foldername>.go - which has the method TestMain which is used for the test. There is only one method TestMain and it is only in the file <foldername>.go 

3) They may have some other go files but it's not required to have them

**Comment by sadov** [comment]
Generally, the main problem is passing some specific arguments for testing binary files. We currently have two ways to do this:
* placing them in the local eden-config.yaml for this test, for ex.:
https://github.com/lf-edge/eden/blob/master/tests/reboot/eden-config.tmpl
* use of test arguments in test scripts or a selected test from an executable binary test for ex.:
https://github.com/lf-edge/eden/blob/master/tests/integration/eden.integration.tests.txt

The second option is more flexible, because we can run the same test several times with different parameters in the single scenario. In the current implementation, we should have a test binary, a test script (in the simplest case, it can have only one line) and eden-config.yaml with their settings for the fully functional `eden test` for this directory. In the opposite way -- you can configure all this simply with the `eden test` options by hand.

**Comment by mydatascience** [comment]
The arguments should be passed either in https://github.com/lf-edge/eden/blob/master/tests/reboot/eden-config.tmpl or directly in command-line for a single test

**Comment by sadov** [comment]
It's possible now.

**Comment by rvs** [comment]
I think all that is needed here is an agreement to:
  1. have a well defined naming convention for test arguments
  2. have a way of clearly finding out what tests arguments a given test uses (think of it as --help for tests)
  3. have a way to override eden-config.yaml from command line

Btw, speaking of #3 -- I'd suggest renaming it to simply config.yaml

**Comment by sadov** [comment]
> I think all that is needed here is an agreement to:
> 
> 1. have a well defined naming convention for test arguments

Sure -- good convention may be very helpful for users of tests.

> 2. have a way of clearly finding out what tests arguments a given test uses (think of it as --help for tests)

Every option just standard self-documented Go flag. It's possible to get such descriptions by calling test binary with '-h' option. 

> 3. have a way to override eden-config.yaml from command line
> 
> Btw, speaking of #3 -- I'd suggest renaming it to simply config.yaml

We previously had such a naming convention, but config.yaml is too abstract and could potentially conflict by name with some kind of YAML configuration that might be needed for some tests for ex. to configure applications. The name eden-config.yaml seems more specific and secure in this case.

**Comment by rvs** [comment]
All makes sense -- on eden-config.yml vs. config.yml -- I think we're fine for now, but once the tests move to EVE repository it may be a bit odd to have a config file eden-config.yml  there. We may want to rename it to test-config.yml or something -- but lets worry about that later, ok? @sadov

**Comment by mydatascience** [comment]
Done
