### ISSUE TITLE
Need to make eden tests print help

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#121]
I remember @sadov mentioning that one can ask an individual test binary to print its own help (all the flags that it accepts at least). However, I could manage to make it do that:

```
$ ./tests/lim/eden.lim.test-darwin-amd64 -h
Log/Info/Metric Test
FATA[0000] cannot parse mode (not [file|proto|adam|zedcloud]://<URL>):
```

Lets make sure to fix that AND also teach eden test to do the same (either via existing -h option or something else):

```
$ ./eden test tests/lim -h
Run tests from test binary. Verbose testing works with any level of general verbosity above "info"

test [test_dir] [-s <scenario>] [-t <timewait>] [-v <level>]
test [test_dir] -l <regexp>
test [test_dir] -r <regexp> [-t <timewait>] [-v <level>]

Usage:
  eden test [test_dir] [flags]

Flags:
  -a, --args string       Arguments for test binary
  -h, --help              help for test
  -l, --list string       list tests matching the regular expression
  -p, --prog string       program binary to run tests
  -r, --run string        run only those tests matching the regular expression
  -s, --scenario string   scenario for tests bunch running
  -t, --timeout string    panic if test exceded the timeout

Global Flags:
      --config-file string   path to config file (default "/Users/roman/.eden/contexts/default.yml")
  -v, --verbosity string     Log level (debug, info, warn, error, fatal, panic (default "info")
```

At this point I'd really like to see flags applicable to test/lim

**Comment by sadov** [comment]
Yes, this is a problem, or rather, a lot of problems. The main problem is the func TestMain which we use in our tests accordingly:
https://wiki.lfedge.org/display/EVE/EVE+Integration+Testing
In fact, to perform this function, we must have a fully pre-configured eden system. Otherwise, we will see one or another error message.
And the second problem is the initialization of the vars flags and the runtime test system only in the m.Run () function. If you have not fully configured the environment, you will see errors before the help message.
The most simple way to solve this problem is to complete the following steps:
```
make build
eden config add default
eden setup
eden start
eden eve onboard
```
and changing the directory to tests/lim (since some configuration parameters are located in the local eden-config.yml file in this directory). In this case, you should get a help message:
```
$ cd tests/lim/
$ ./eden.lim.test -h
Log/Info/Metric Test
Usage of ./eden.lim.test:
  -number int
    	The number of items (0=unlimited) you need to get (default 1)
....
  -timewait int
    	Timewait for items waiting in seconds (default 60)
```
I understand - this is not a very easy way for such general actions as getting help, and we need to create a simpler solution. Maybe for this we need to redesign our basic pseudo code template for test writing.

**Comment by rvs** [comment]
OK, so how about we introduce that `eden test XXX -h` now that would literally do that cd and run the test executable with -h?

**Comment by sadov** [comment]
Actually `eden test XXX -h` reserved by Cobra for general help message. I added the option '-o|--opts' for this and new readme file about testing: https://github.com/itmo-eve/eden/blob/test_opts/TESTING.md
