### ISSUE TITLE
log and info commands should have default for the location of the log and info directory

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#29]
Both of these commands currently require me to pass two arguments a query and a location of the directory in the filesystem. The directory part should:
   * have a default (that gets figured out from a running Adam instance)
   * be tweakable by the `-dir` flag

The query part should also have a default

IOW, I should be able to run: `eden log` or `eden info` and get the expected result.

**Comment by sadov** [comment]
To implement this, we need to know the UUID of the device, because the path to the log/info directory depends on it, and perhaps we can have several EVE instances connected to ADAM. In the current implementation, we must set this path as the first parameter - this is described in the corrected command's helps.

**Comment by sadov** [comment]
Helps fixed on [PR43](https://github.com/lf-edge/eden/pull/43).
