### ISSUE TITLE
We need to migrate away from file-based log and info gathering

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#42]
Currently Eden tries to follow logs and info messages that Adam collects through the filesystem. We need to migrate to something other than that and make sure that we can query Adam itself for that information. I'm sure @deitch will have an opinion here, but I'm thinking something like an embedded https://github.com/unit-io/tracedb into Adam.

What do you think @giggsoff @sadov -- can you guys articulate your requirements on this issue?

**Comment by deitch** [comment]
I am going to draw out the picture as I understand it, both current state and desired. Let's ensure that it is correct, and then we can propose solutions.

### Current

Adam has a "driver" - currently supports memory and filesystem - where it stores information about devices, including (relevant to this discussion): info and logs.

eden's `log` and `info` commands (and their `*watch` variants) take an argument of a log file to parse. Essentially, `eden log <file>` is a smart log file parser; same for info.

To make this work you need to:

1. start the controller and device (e.g. via eden)
1. find the correct output file
1. pass the output file to eden via `eden log <filename>`

### Desired State

Independently of what we do here, the above functionally actually is quite useful, e.g. if we have a log file from elsewhere that we want to parse.

For normal eden functionality, though, we want this built into the inherent knowledge that eden has about running devices and controllers.

Our experience would look something like:

```console
$ eden log <device> [<args>]
```

Rather than needing to feed it the _file_, which we would have to find, we would just feed it the device ID, of which eden already is fully aware.

### Proposal

If the above is correct, I would propose the following:

1. Expose adam endpoints (when running as a server, of course) to get and/or stream logs and info for a device. This will abstract away the "file vs memory vs any other future driver" question, simplifying eden. It also will remove from the eden user the burden of finding the particular log file.
1. Construct eden to consume those adam endpoints. I would keep the file-based functionality we have now as an option; I really like the fact that I can sanely parse a log file using just eden, even without any running controllers or devices.

Once the above is done, I would look at embedding tracedb into adam. It wouldn't change anything for eden (at least initially), as it would be under-the-covers of adam. Eventually, we might improve the endpoints to make its usage more powerful. But one step at a time, methinks.

Does that sound about right?

**Comment by rvs** [comment]
This is exactly right @deitch -- 100% agreed! Two additional points tho:
   * can you do a quick hack to at least expose raw files via http endpoint (e.g. just adding `http.FileServer(http.Dir(directory)` and hanging it off of an endpoint of some sorts?
   * @giggsoff @sadov how quickly do you think you can update Eden test harness to actually consume those files off of an http end point and not from the filesystem?

I need the above pretty soon for my use case of running EVE testing on Google cloud. The problem is that I have a testdriver that runs on my laptop, but both EVE and Adam run in the Google cloud and setting up some kind of sshfs or heaven forbid nfs is really inconvenient.

The rest of the plan I agree with wholeheartedly, but I really would like to hear @giggsoff @sadov describing what would be an ideal API for them (simple range queries, streaming queries, something else?).

Finally, tracedb was just a quick suggestion on my part -- if y'all know something better or something you like more -- feel free to suggest.

**Comment by deitch** [comment]
Already working on it @rvs

**Comment by sadov** [comment]
At first, some explanations about the current status of the 'info/log' commands described by @deitch -- unfortunately, when switching from separate utilities to single application, some helps was lost, and we are fixing it now. Actually, now we using regular expression queries to find some data related to fields in json info/log files. And for selecting of files related to device UUID we may use request:
eden log some_file devId:dd0657ff-69c4-47ff-bf03-3da7e00eeb77
Possibly in the future, it would be wise to look in the directory, not in the file, as we do in log/infowatch.

**Comment by sadov** [comment]
About the @rvs  proposal - yes, using an HTTP server to access info/log files seems not very hard to implement at this stage. We just need to synchronize the corresponding directories from ADAM via HTTP from time to time and jus work with local mirrors of such directories. But in the future, it would be reasonably to think of some kind of subscription service in order to avoid continuous polling of the HTTP server. Seems the tracedb-related tool 'trace' seems to be a good solution for this - as far as I understand, it supports the MQTT protocol.

**Comment by deitch** [comment]
I will have an implementation for Adam exposing an API to access logs and info by the end of the day today. We can then expand it from there.

**Comment by sadov** [comment]
Great!

**Comment by sadov** [comment]
Fixed at [PR50](https://github.com/lf-edge/eden/pull/50)
