### ISSUE TITLE
We need to provide asynchronous asserts in Eden framework

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#45]
While looking at a few Eden tests it became clear to me that a we need to implement asynchronous asserts and in general encourage the test writers to write their tests with EVE's eventual consistency in mind.

Let me explain. Fundamentally, testing EVE is about the following 3 things:
   1. crafting a certain config based on the desired state that the test wants to validate
   2. monitoring EVE's state transition for valid (and invalid transitions)
   3. monitoring other state (outside of EVE) for desired properties

We are now starting to look good when it comes to automation of №1, and with log and info messages from Adam now moving to a continuous streaming architecture it is time we tackle №2.

The way I suggest we do it is -- we rely on two worker threads that always start when we initialize any controller/cloud object. Those worker threads are in business of continuously receiving log and info messages from the controller. What I'm suggesting is that we should make it possible to register listeners on these worker threads and make it convenient for test writers to create asserts that are attached to those listeners. Think of the asserts as validating (or invalidating!) the stream of info messages (and later logs).

E.g. instead of blocking like we currently do https://github.com/lf-edge/eden/blob/master/tests/integration/baseImage_test.go#L63 we will write a code similar to:

```
    deviceCtx.InfoAssertOnce("wait for version", filter.ZInfoDevSW, func(i InfoType) bool {i.version == desiredVersion})
```

This type of assert InfoAssertOnce is expected to fire once and when it does it is expected to go way (obviously it does have a chance to either pass or fail). At the end of the test run all these kinds of asserts that haven't passed are considered failed.

In addition we can also have a continuous type of assert -- the kind that simply listens and validates the events as they flow -- those types of asserts will persist until the end of the test run and then will have a chance to run one last time signaling the end of a testrun.

Obviously, we should also implement assert management that would allow us to block (if needed) on certain sets of asserts firing, etc.

I'd love to hear @deitch if he's seen any test frameworks like that -- if not -- it shouldn't be to difficult to implement from scratch.

Implementation-wise, I'm not sure whether all these asserts need their own goroutines and be fed events via channels or something else may be simpler/faster.

**Comment by sadov** [comment]
Currently, we have some improvements (which we plan to place in the next PR) as an implementation of the functions described in the “dev. workflow” issue (https://github.com/lf-edge/eden/issues/22): to load the image of the base OS, send the JSON configuration to EVE and running the test binary with the` eden test` command.

And actually, we have a preliminary implementation of such asynchronous behavior:
https://github.com/itmo-eve/eden/blob/test_hooks/tests/integration/hooks_test.go
This is currently not very convenient, because we need to create description of such parallel tests on the some complex EdenHooks structure. It will be more interesting to implement some testing module that will read the test script from a text file. It seems reasonable to think about implementing one of two ways, or there might be some combination of both of them. Any such improvements will have to use more or less large pieces of code from the Go compiler.

One possible way is to use some internal Go functionality embedded in the `test` command. We must use the unexported module `parse` and possibly some related modules. Thus, we will parse the sources of our Go test files (as is done in the `go test` command) and automatically fill out such a structure.

Another way is to use a testing technique that allows you to write test scripts in the form of text files:
https://github.com/golang/go/tree/master/src/cmd/go/testdata/script
https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript
Now we are looking at the adoption of this machinery for EDEN -- we can just run the `eden` ​​commands and some binary tests (if necessary) on a test script (as a background process too) and check the results.

We would be very interested to know your opinion @rvs and @deitch

**Comment by deitch** [comment]
So as I understand it, you want to have asynchronous tests but with a synchronous feel. I should be able to run some command to trigger behaviour, and immediately register a handler for checking results. At the end of all triggered tests, something waits, perhaps with a timeout, for all of the results:

```go
// this runs synchronously
eden.RunSomeCommand(deviceID)
// this registers the handler and returns immediately, even though the result is not done yet
eden.CheckDeviceStatus(deviceID, someStateTransition, func(){ ... })
```

The `func` handler in `CheckDeviceStatus` (or whatever we call it) gets called when some state transition occurs, and returns (success|failure and an error message).

At the end of all tests, something like:

```go
eden.WaitForAllTests()
```

which waits for all registered async tests.

I haven't seen anything like this in go (although it must exist). The last really good framework I saw for that was in javascript, with its heavy asynchronicity (that is a word; I just decided). It has been a while since I delved too deeply into that world, but https://mochajs.org always had some serious async heft, and TJ Holowaychuk's supertest could do some of it as well.

**Comment by sadov** [comment]
So guys - I created some simple machinery to run sets of asynchronous tests:
https://github.com/itmo-eve/eden/blob/tests_set/tests/integration/tests_set.go

All tests in this tests set are executing by a separate goroutine, and all of them are completed after finishing of any test in this test set. The cumulative result of this test for the complete test set is just a result of this first finished test. Generally, you just need to create test functions and describe your test set (name, function, arguments and regular expression for the return value) in the ETests map.  A simple example that you can see here:
https://github.com/itmo-eve/eden/blob/tests_set/tests/integration/testset_test.go

You can start them by `eden` from our test binary:
`./eden test -r TestSets/BoolTest -v debug`
or by traditional Go test procedure:
`go test tests/integration/testset_test.go tests/integration/tests_set.go tests/integration/common.go -run=TestSets/BoolTest -v`

The RebootTest test in this example will finish work after rebooting the EVE or timeout exceeding:
`./eden test -r TestSets/RebootTest -v debug`

**Comment by mydatascience** [comment]
Closing as we did it, I believe
