### ISSUE TITLE
sometimes EVE update from OCI fails with the error

### ISSUE THREAD

**Issue by giggsoff** [lf-edge/eden#571]
# Description
When we try to update EVE with OCI image, we get errors inside info messages from time to time.

# Steps to Reproduce
`make run&&./eden eve onboard&&./eden controller edge-node eveimage-update oci://lfedge/eve:6.0.0-kvm-amd64`

# Actual Results
Inside `./eden info` I see
```
swErr:{description:"installDownloadedObject(8690033b-27c4-4a50-afff-57d4f539e4e5): InstallWorkResult error, exception while installing: error pulling 8690033b-27c4-4a50-afff-57d4f539e4e5-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528 from containerd: image \"8690033b-27c4-4a50-afff-57d4f539e4e5-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\": not found" timestamp:{seconds:1616759105 nanos:839339803}
```

# Expected Results
No errors inside info.

# Additional information
Attempt to remove volumeID fix the problem (https://github.com/lf-edge/eden/pull/568), but it is [deprecated](https://github.com/lf-edge/eve/blob/fe8e7e7190d86019a1570a4f0fa97c396382af44/api/go/config/baseosconfig.pb.go#L112) method.

Log (debug) and Info attached:
[oci.log](https://github.com/lf-edge/eden/files/6229873/oci.log)
[oci.info.log](https://github.com/lf-edge/eden/files/6229874/oci.info.log)

**Comment by deitch** [comment]
What does this part mean, @giggsoff ?

> Attempt to remove volumeID fix the problem

Attempting to remove the volumeID? From what? How did it fix it?

**Comment by deitch** [comment]
I have a suspicion that the problem has to do with all of the content being available, but the image not yet created. This is because it looks like it does it twice. Look at these log lines:

```json
{"severity":"info",
"source":"zedagent",
"iid":"1496",
"content":"{\"content-sha256\":\"\",\"datastore-id\":\"e9aab490-c4a8-4802-905d-97d566bb9596\",\"file\":\"/pillar/types/contenttreetypes.go:45\",\"format\":8,\"func\":\"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeConfig.LogCreate\",\"level\":\"info\",\"log_event_type\":\"log\",\"max-download-size-int64\":0,\"msg\":\"Content tree config create\",\"obj_key\":\"contenttree_config-acb65d45-1193-4186-9a81-070a58fb89f9\",\"obj_name\":\"lfedge/eve:6.0.0-kvm-amd64\",\"obj_type\":\"contenttree_config\",\"obj_uuid\":\"acb65d45-1193-4186-9a81-070a58fb89f9\",\"pid\":1496,\"relative-URL\":\"lfedge/eve:6.0.0-kvm-amd64\",\"source\":\"zedagent\",\"time\":\"2021-03-26T11:43:03.239585851Z\"}\n",
"msgid":1372,
"timestamp : {"seconds":1616758983,"nanos":239585851},
"filename":"/pillar/types/contenttreetypes.go:45",
"function":"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeConfig.LogCreate"
}
```

and 

```json
{"severity":"info",
"source":"baseosmgr",
"iid":"1496",
"content":"{\"content-sha256\":\"\",\"datastore-id\":\"e9aab490-c4a8-4802-905d-97d566bb9596\",\"file\":\"/pillar/types/contenttreetypes.go:45\",\"format\":8,\"func\":\"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeConfig.LogCreate\",\"level\":\"info\",\"log_event_type\":\"log\",\"max-download-size-int64\":0,\"msg\":\"Content tree config create\",\"obj_key\":\"contenttree_config-8690033b-27c4-4a50-afff-57d4f539e4e5\",\"obj_name\":\"lfedge/eve:6.0.0-kvm-amd64\",\"obj_type\":\"contenttree_config\",\"obj_uuid\":\"8690033b-27c4-4a50-afff-57d4f539e4e5\",\"pid\":1496,\"relative-URL\":\"lfedge/eve:6.0.0-kvm-amd64\",\"source\":\"baseosmgr\",\"time\":\"2021-03-26T11:43:03.271787789Z\"}\n",
"msgid":1494,
"timestamp":{"seconds":1616758983,"nanos":271787789},
"filename":"/pillar/types/contenttreetypes.go:45",
"function":"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeConfig.LogCreate"}
```

As far as I can tell, within about 50ms of each other,  _two_ `ContentTreeConfig` are created. One is by zedagent, the other is by baseosmgr. The one by baseosmgr is the one that sometimes doesn't appear. 

Why would we have two `ContentTreeConfig`?

Admittedly, baseosmgr should be able to handle this case, and I am working on finding where it gets tripped up, but this doesn't look quite right to me.

@eriknordmark does this say anything to you?

**Comment by deitch** [comment]
Something else I do not understand. This appears at line 7486 in the log:

```json
{"severity":"info",
"source":"baseosmgr",
"iid":"1496",
"content":"{\"content-sha256\":\"62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\",\"file\":\"/pillar/types/contenttreetypes.go:208\",\"filelocation\":\"\",\"func\":\"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeStatus.LogModify\",\"level\":\"info\",\"log_event_type\":\"log\",\"max-download-size-int64\":0,\"msg\":\"Content tree status modify\",\"obj_key\":\"contenttree_status-8690033b-27c4-4a50-afff-57d4f539e4e5\",\"obj_name\":\"lfedge/eve:6.0.0-kvm-amd64\",\"obj_type\":\"contenttree_status\",\"obj_uuid\":\"8690033b-27c4-4a50-afff-57d4f539e4e5\",\"old-content-sha256\":\"62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\",\"old-filelocation\":\"/persist/vault/verifier/verified/62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\",\"old-max-download-size-int64\":0,\"old-progress\":100,\"old-state\":\"LOADING\",\"pid\":1496,\"progress\":100,\"source\":\"baseosmgr\",\"state\":\"LOADED\",\"time\":\"2021-03-26T11:45:05.666437034Z\"}\n",
"msgid":7486,
"timestamp":{"seconds":1616759105,"nanos":666437034},
"filename":"/pillar/types/contenttreetypes.go:208",
"function":"github.com/lf-edge/eve/pkg/pillar/types.ContentTreeStatus.LogModify"
}
```

What does it mean that it changed the `ContentTreeStatus` from LOADING to LOADED? It says the "source" is "baseosmgr". But shouldn't it be volumemgr that updates the `ContentTreeStatus`? Or did I misunderstand what the log message means?

**Comment by deitch** [comment]
Ok, I think I have it. Here is what happens:

1. We request to install the baseos from an image, e.g. `lfedge/eve:6.0.0-kvm-amd64`
2. For reasons unknown (see above), we get **two** requests for content trees based on that image: one from zedagent, the other from baseosmgr. This should **not** be happening. Nonetheless, baseosmgr should be able to handle it.
3. Both get their manifests downloaded, all of the hashes inside get created as `DownloaderConfig`. These are downloaded exactly once, due to the deduplication we have.
4. All of them eventually get downloaded, verified.
5. `updatestatus` tries to load them into containerd and create an image reference for them. This happens for _each_ of the two content trees
6. The first one (whichever that is, usually the odd one from zedagent) loads all of its blobs into containerd, creates an image in containerd named `<UUID>-lfedge/eve@sha256:<hash>`.
7. In parallel, actually just slightly later, often <200 ms or even less, the second one (usually the one from baseosmgr) loads all of its blobs into containerd, creates an image in containerd named `<UUID>-lfedge/eve@sha256:<hash>`. `<hash>` between these two is identical, but `<UUID>` is different.
8. Upon return from load, each of them calls [updateStatusByBlob](https://github.com/lf-edge/eve/blob/a8c5dddf242095210736c20f465f6fb26e23db65/pkg/pillar/cmd/volumemgr/updatestatus.go#L554). This finds _all_ of the `ContentTreeStatus` which have those blobs and updates them and publishes them
9. This in turn calls [doUpdateContentTree](https://github.com/lf-edge/eve/blob/a8c5dddf242095210736c20f465f6fb26e23db65/pkg/pillar/cmd/volumemgr/updatestatus.go#L21), the core loop, for _both_ of the `ContentTreeStatus`. 
10. In parallel, in the background, the second (as-yet-unfinished) "load and create image" may still be running, or may be complete
11. [doUpdateContentTree](https://github.com/lf-edge/eve/blob/a8c5dddf242095210736c20f465f6fb26e23db65/pkg/pillar/cmd/volumemgr/updatestatus.go#L21) runs through all of the blobs, sees that they are loaded, says, "oh, I am done!", changes `ContentTreeStatus.STATE` to "LOADED", and publishes it.
12. baseosmgr sees the update to LOADED, tries to retrieve the image based on `<UUID>-lfedge/eve@sha256:<hash>` from containerd.

Because the blobs are _identical_ for both trees, the second to last step sometimes can happen quickly enough that the second tree has not quite yet completed creating its image reference in containerd, before the last step occurs. We get "no image found".

**Comment by deitch** [comment]
Now that we know the root cause, I need to think of the best response. I think that we need to make the `doUpdateContentTree` be smart enough that it only will change `ContentTreeStatus.STATE` when it has _both_ all blobs loaded _and_ image created. We cannot simply do, "oh, we found all blobs for this tree, so let's consider it done."

Going to let it sit for a day or two and get feedback.

**Comment by deitch** [comment]
That turned out to be simpler than I thought. PR coming shortly to eve.
